# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderImage', models.ImageField(upload_to='../images/')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='love.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(default='note')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='answerFive',
            field=models.TextField(default='Answer to question five'),
        ),
        migrations.AddField(
            model_name='order',
            name='answerFour',
            field=models.TextField(default='Answer to question four'),
        ),
        migrations.AddField(
            model_name='order',
            name='answerOne',
            field=models.TextField(default='Answer to question one'),
        ),
        migrations.AddField(
            model_name='order',
            name='answerThree',
            field=models.TextField(default='Answer to question three'),
        ),
        migrations.AddField(
            model_name='order',
            name='answerTwo',
            field=models.TextField(default='Answer to question two'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='love.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streetAddress',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zipCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='love.Order'),
        ),
        migrations.AddField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='love.User'),
        ),
    ]
