# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0002_auto_20160914_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='love.Order'),
        ),
        migrations.AlterField(
            model_name='note',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='love.Order'),
        ),
        migrations.AlterField(
            model_name='note',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='love.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
