# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0003_auto_20160914_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='orderId',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='orderId',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userId',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='orderImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
